export default [
  'Agile',
  'Stakeholder Interviews',
  'Creativity',
  'Data Driven Decisions',
  'Accessibility First',
  'Shadow DOM',
  'Continuous integration',
  'Machine Learning',
  'Pair programming',
  'Version Control',
  'React',
  'Innovation',
  'Redux',
  'SOA architectures',
  'Angular',
  'Jest',
  'SQL',
  'Visual regression testing',
  'Snapshot testing',
  'React Native',
  'RxJS',
  'Team Work',
  'Forward thinking',
  'Leadership',
  'Trunk-based Development',
  'REST API',
  'Async functions'
]
